version: '3.8'
services:
  payoorserver:
    container_name: payoorserver
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/data/certs:/etc/nginx/certs
    depends_on:
      - payoorapi

  payoorapi:
    container_name: payoorapi
    restart: always
    build: ./api
    environment:
      - PORT=8080
